Repository ya-pomogau/backend, pull requests merged in 2023-12, with the labels that each got.

#53 Refactor/use env and configmodule
  .env.example
  obsolete/features/tsconfig.build.tsbuildinfo
  src/app.module.ts
  src/common/hash/hash.service.ts
  src/common/types/system.types.ts
  src/config/configuration.ts
  src/config/database-config.factory.ts
  src/config/database-config.service.ts
  src/core/auth/auth.module.ts
  src/core/auth/auth.service.ts
Labels: backend

#54 [Feature] Auth flow
  package-lock.json
  package.json
  src/api/auth-api/auth-api.controller.ts
  src/api/auth-api/auth-api.service.ts
  src/api/auth-api/dto/vk-login.dto.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/common/decorators/public.decorator.ts
  src/common/dtos/tasks.dto.ts
  src/common/guards/jwt-auth.guard.ts
  src/common/guards/local-auth.guard.ts
  src/common/types/api.types.ts
  src/common/types/express/index.d.ts
  src/common/types/system.types.ts
  src/common/types/user.types.ts
  src/config/configuration.ts
  src/config/database-config.service.ts
  src/core/auth/strategies/jwt.strategy.ts
  src/core/auth/strategies/local.strategy.ts
  src/core/tasks/tasks.module.ts
  src/core/tasks/tasks.service.ts
  src/core/users/users.service.ts
  src/datalake/users/schemas/admin.schema.ts
  src/datalake/users/schemas/user.schema.ts
  src/datalake/users/users-testcontroller.controller.ts
Labels: feature, backend

#55 исправила dto
  src/api/auth-api/dto/vk-login.dto.ts
  src/api/auth-api/dto/vk-new.dto.ts
Labels: bug
