Repository ya-pomogau/backend, pull requests merged in 2023-11, with the labels that each got.

#30 Сделал модуль Contacts
  .eslintrc.js
  .prettierrc
  src/common/types/ContactsDataDTO.ts
  src/datalake/contacts/contacts.module.ts
  src/datalake/contacts/contacts.service.ts
  src/datalake/contacts/dto/create-contact.dto.ts
  src/datalake/contacts/schemas/contact.schema.ts
Labels: feature, backend

#37 Сделал норм enum в схеме Категорий
  src/datalake/category/category.module.ts
  src/datalake/category/schemas/category.shema.ts
Labels: bug, backend

#31 Сделал datalake BlogPost
  src/common/schemas/PointGeoJSON.schema.ts
  src/common/types/BlogPostDataDTO.ts
  src/common/types/UsersDataDTO.ts
  src/common/types/user.types.ts
  src/datalake/blog-post/blog-post.module.ts
  src/datalake/blog-post/blog-post.service.ts
  src/datalake/blog-post/dto/create-blog-post.dto.ts
  src/datalake/blog-post/dto/update-blog-post.dto.ts
  src/datalake/blog-post/schema/blog-post.schema.ts
Labels: feature, backend

#38 [Feature]
  .gitignore
  src/common/types/pojo.type.ts
  src/datalake/base-repository/base-repository.service.ts
Labels: feature, backend

#42 [Hotfix] Get rid up of old base-repository.ts
  src/datalake/base-repository/base-repository/base-repository.ts
Labels: bug, backend

#40 [Refactor] Adopt BaseRepository
  src/common/types/category.types.ts
  src/common/types/task.types.ts
  src/datalake/category/category.module.ts
  src/datalake/category/category.repository.ts
  src/datalake/category/category.service.ts
  src/datalake/category/dto/create-category.dto.ts
  src/datalake/category/dto/update-category.dto.ts
  src/datalake/category/schemas/category.schema.ts
  src/datalake/category/schemas/category.shema.ts
  src/datalake/task/schemas/task.schema.ts
Labels: backend

#34 Feat/datalake user
  .prettierrc1111
  src/common/constants/exceptions.ts
  src/common/hash/hash.service.ts
  src/common/types/UsersDataDTO.ts
  src/common/types/user.types.ts
  src/datalake/users/schemas/admin.schema.ts
  src/datalake/users/schemas/recipient.schema.ts
  src/datalake/users/schemas/user.schema.ts
  src/datalake/users/schemas/volunteer.schema.ts
  src/datalake/users/users.module.ts
  src/datalake/users/users.service.ts
Labels: feature, backend

#45 [Refactor] Contacts entity repository adopted to extend BaseRepositoryService
  src/common/dtos/users.dto.ts
  src/common/schemas/user-profile.schema.ts
  src/common/types/ContactsDataDTO.ts
  src/common/types/UsersDataDTO.ts
  src/common/types/contacts.types.ts
  src/common/types/user.types.ts
  src/datalake/base-repository/base-repository.service.ts
  src/datalake/contacts/contacts.module.ts
  src/datalake/contacts/contacts.repository.ts
  src/datalake/contacts/contacts.service.ts
  src/datalake/contacts/dto/create-contact.dto.ts
  src/datalake/contacts/schemas/contact.schema.ts
  src/datalake/users/schemas/admin.schema.ts
  src/datalake/users/schemas/recipient.schema.ts
  src/datalake/users/schemas/user.schema.ts
  src/datalake/users/schemas/volunteer.schema.ts
  src/datalake/users/users.module.ts
  src/datalake/users/users.repository.ts
Labels: backend, refactor
