Repository ya-pomogau/backend, pull requests merged in 2024-10, with the labels that each got.

#203 [Hotfix] Corrected `.addMessage` & some typings
  src/common/types/chats.types.ts
  src/core/chat/chats.service.ts
  src/main.ts
Labels: bug, backend

#207 Feature/send chat messages by socket
  src/api/websocket-api/websocket-api.gateway.ts
  src/api/websocket-api/websocket-api.module.ts
  src/common/queries/get-chat-messages.query.ts
  src/common/queries/index.ts
  src/core/chat/chats.service.ts
  src/core/get-chat-messages-query.handler.ts
Labels: feature, backend

#212 create sendUserChatsMeta method for usage from within the handleConnection method
  src/api/websocket-api/websocket-api.gateway.ts
  src/common/queries/get-user-chats-meta.query.ts
  src/common/queries/index.ts
  src/core/get-user-chats-meta.handler.ts
Labels: feature, backend

#208 Feature/open close chat handlers
  src/api/websocket-api/dto/websocket-opened-chats.dto.ts
  src/api/websocket-api/websocket-api.gateway.ts
  src/common/types/websockets.types.ts
Labels: feature, backend

#213 Рефакторинг мутирующих пользователя методов сервиса пользователя, и использующих их API, c переводом на CQRS.
  src/api/admin-api/admin-api.controller.spec.ts
  src/api/admin-api/admin-api.controller.ts
  src/api/admin-api/admin-api.module.ts
  src/api/admin-api/commands-and-queries/commands.ts
  src/api/system-api/commands-and-queries/commands.ts
  src/api/system-api/system-api.controller.ts
  src/api/system-api/system-api.module.ts
  src/common/commands/activate-user.command.ts
  src/common/commands/block-user.command.ts
  src/common/commands/confirm-user.command.ts
  src/common/commands/create-admin.command.ts
  src/common/commands/deactivate-admin.command.ts
  src/common/commands/downgrade-user.command.ts
  src/common/commands/grant-admin-privileges.command.ts
  src/common/commands/grant-volunteer-keys.command.ts
  src/common/commands/revoke-admin-privileges.command.ts
  src/common/commands/revoke-volunteer-keys.command.ts
  src/common/commands/update-admin-privileges.command copy.ts
  src/common/commands/update-user-profile.command.ts
  src/common/commands/update-volunteer-profile.command.ts
  src/common/commands/upgrade-user.command.ts
  src/core/activate-user.handler.ts
  src/core/block-user.handler.ts
  src/core/confirm-user.handler.ts
  src/core/deactivate-admin.handler.ts
  src/core/downgrade-user.handler.ts
  src/core/grant-admin-privileges.handler.ts
  src/core/grant-volunteer-keys.handler.ts
  src/core/revoke-admin-privileges.handler.ts
  src/core/revoke-volunteer-keys.handler.ts
  src/core/tasks/commands-and-queries/commands.ts
  src/core/tasks/tasks.module.ts
  src/core/tasks/tasks.service.ts
  src/core/update-admin-privileges.handler copy.ts
  src/core/update-user-profile.handler.ts
  src/core/update-volunteer-profile.handler.ts
  src/core/upgrade-user.handler.ts
  src/core/users/users.service.ts
Labels: backend, PR

#214 Рефакторинг ручек возврата списков активных, заблокированных (деактивированных) и всех администраторов #209
  src/api/admin-api/admin-api.controller.ts
  src/core/users/users.service.ts
Labels: backend, refactor, PR
