Repository ya-pomogau/backend, pull requests merged in 2024-09, with the labels that each got.

#142 Feat/change points in active tasks
  src/api/admin-api/dto/bulk-update-categories.dto.ts
  src/api/admin-api/dto/update-category.dto.ts
  src/common/commands/update-points.command.ts
  src/core/categories/categories.module.ts
  src/core/categories/categories.service.ts
  src/core/categories/commands-and-queries/commands.ts
  src/core/tasks/tasks.service.ts
  src/core/update-points.hadler.ts
Labels: bug

#193 change chat.types ObjectId to import from mongoose
  src/common/types/chats.types.ts
  src/core/chat/chats.service.ts
Labels: bug, backend

#195 feat: prepare gateway for concurrently development
  src/api/websocket-api/websocket-api.gateway.ts
  src/common/types/websockets.types.ts
  src/core/chat/chats.service.ts
Labels: feature, backend
