Repository ya-pomogau/backend, pull requests merged in 2024-03, with the labels that each got.

#71 Add postman collection file
  README.md
  postman_collection.json
Labels: feature, backend

#70 bulkWrite переделан на Promise.all
  src/core/categories/categories.module.ts
  src/core/categories/categories.service.ts
Labels: backend, refactor

#81 hotfixes/volunteer-api/get-virgin-rights-acl/plus
  src/api/admin-api/admin-api.controller.ts
  src/api/volunteer-api/volunteer-api.controller.ts
  src/common/constants/mongoose-fields-raw-definition.ts
  src/datalake/base-repository/base-repository.service.ts
Labels: bug, backend, refactor

#76 [Feature] PolicyModule
  src/api/admin-api/admin-api.controller.ts
  src/api/system-api/system-api.controller.ts
  src/api/system-api/system-api.module.ts
  src/app.module.ts
  src/common/filters/methodNotAllowedFilter.ts
  src/core/categories/categories.service.ts
  src/core/policy/policy.module.ts
  src/core/policy/policy.service.ts
  src/datalake/confidentiality-policy/policy-repository.module.ts
  src/datalake/confidentiality-policy/policy.repository.ts
Labels: feature, backend

#75 [Feature] ContactsModule
  src/api/recipient-api/recipient-api.controller.ts
  src/api/system-api/system-api.controller.ts
  src/api/system-api/system-api.module.ts
  src/app.module.ts
  src/core/categories/categories.service.ts
  src/core/contacts/contacts.module.ts
  src/core/contacts/contacts.service.ts
  src/core/tasks/tasks.service.ts
  src/datalake/contacts/contacts-repository.module.ts
  src/datalake/contacts/schemas/contact.schema.ts
  src/datalake/task/task-repository.module.ts
Labels: feature, backend

#86 [Hotfix] Specified level for ACL for /recipient/tasks/:id handle
  src/api/recipient-api/recipient-api.controller.ts
Labels: bug, backend

#87 Небольшие правки ручек категорий
  src/api/admin-api/admin-api.controller.ts
Labels: bug
