Repository ya-pomogau/backend, pull requests merged in 2024-08, with the labels that each got.

#145 Refactor/chats/move interfaces to src common types
  src/common/dtos/get-chats-info.response.dto.ts
  src/common/types/chat.types.ts
  src/common/types/chats.types.ts
  src/datalake/chat/chat.module.ts
  src/datalake/chat/chat.service.ts
  src/datalake/chat/schemas/chat.schema.ts
  src/datalake/chat/schemas/message.schema.ts
Labels: backend

#144 Реализация Pipe для валидации сокета (задача #141)
  src/api/system-api/system-api.gateway.ts
  src/common/pipes/socket-validation.pipe.ts
  src/core/blog/blog.service.ts
Labels: feature, backend

#146 [New] WebSockets message types
  src/common/types/websockets.types.ts
Labels: feature, backend

#147 Correct updates of discriminated collection
  src/core/users/users.service.ts
Labels: backend

#162 Реализация отправки токена по сокету
  .env.example
  src/api/admin-api/admin-api.module.ts
  src/api/auth-api/auth-api.controller.ts
  src/api/system-api/system-api.gateway.ts
  src/common/commands/authenticate.command.ts
  src/common/commands/send-token.command.ts
  src/common/types/system.types.ts
  src/common/types/websockets.types.ts
  src/config/configuration.ts
  src/core/auth/auth.service.ts
  src/core/send-token.handler.ts
  src/core/tasks/tasks.service.ts
  src/core/users/commands-and-queries/commands.ts
  src/core/users/users.module.ts
  src/core/users/users.service.ts
Labels: feature, backend

#159 Создание ручки получения всех задач произвольного пользователя для AdminApi (задача 155)
  src/api/admin-api/admin-api.controller.spec.ts
  src/api/admin-api/admin-api.controller.ts
Labels: feature
