Repository ya-pomogau/backend, pull requests merged in 2024-07, with the labels that each got.

#114 [Fix] Got rid of password in response while creating admin
  src/core/users/users.service.ts
Labels: backend

#113 [Refactor] Introducing CQRS
  package-lock.json
  package.json
  src/api/auth-api/auth-api.controller.ts
  src/api/auth-api/auth-api.module.ts
  src/api/auth-api/commands-and-queries/commands.ts
  src/common/commands/authenticate.command.ts
  src/common/commands/check-jwt.command.ts
  src/common/commands/create-user.command.ts
  src/common/commands/login-user.command.ts
  src/core/authenticate.handler.ts
  src/core/check-jwt.handler.ts
  src/core/create-user.handler.ts
  src/core/login-user.handler.ts
Labels: backend, refactor

#108 Refactor/tasks/account points and tasks for volunteer
  src/common/types/task.types.ts
  src/common/types/user.types.ts
  src/core/tasks/tasks.module.ts
  src/core/tasks/tasks.service.ts
  src/core/users/users.service.ts
  src/datalake/users/schemas/volunteer.schema.ts
Labels: refactor

#109 Refactor/categories bulk edit
  src/api/admin-api/admin-api.controller.ts
  src/api/admin-api/dto/bulk-update-categories.dto.ts
  src/common/helpers/checkIsEnoughRights.ts
  src/common/types/category.types.ts
  src/core/categories/categories.service.ts
Labels: refactor

#118 [Feature] Chats info dto interfaces
  src/common/dtos/get-chats-info.response.dto.ts
Labels: feature, backend

#117 Создание Websockets gateway для системных сообщений
  src/api/system-api/system-api.gateway.ts
  src/api/system-api/system-api.module.ts
  src/core/create-user.handler.ts
Labels: feature

#133 [Fix] Added `status` to create user response
  src/core/users/users.service.ts
Labels: bug, feature, backend

#136 [Fix] Corrected `UsersService.deactivate()` to work with discriminated collection
  src/core/users/users.service.ts
Labels: bug, backend

#134 Изменение permissions у админа (задача #131)
  src/api/admin-api/admin-api.controller.ts
  src/api/system-api/system-api.gateway.ts
  src/common/constants/exceptions.ts
  src/common/dto/category.dto.ts
  src/core/tasks/tasks.service.ts
  src/core/users/users.service.ts
  src/datalake/category/schemas/category.schema.ts
  src/datalake/users/users-testcontroller.controller.ts
Labels: feature, backend

#129 feat: add socket auth guard, check token at SystemApiGateway
  .eslintrc.js
  src/api/system-api/system-api.gateway.ts
  src/common/guards/socket-auth.guard.ts
Labels: feature, backend
